
// Array of project objects containing project details
const projects = [
    { 
        title: "Generative Quanta Color Imaging",
        imageUrl: "https://via.placeholder.com/150",
        url: "https://vishal-s-p.github.io/projects/2023/proj_1.html",
        abstract: "The astonishing development of single-photon cameras has created an unprecedented opportunity for scientific and industrial imaging. However, the high data throughput generated by these 1-bit sensors creates a significant bottleneck for low-power applications. In this paper, we explore the possibility of generating a color image from a single binary frame of a single-photon camera. We evidently find this problem being particularly difficult to standard colorization approaches due to the substantial degree of exposure variation. The core innovation of our paper is an exposure synthesis model framed under a neural ordinary differential equation (NeuralODE) that allows us to generate a continuum of exposures from a single observation. This innovation ensures consistent exposure in binary images that colorizers take on, resulting in notably enhanced colorization. We demonstrate applications of the method in single-image and burst colorization and show superior generative performance over baselines."
    },
    // { 
    //     title: "Project 2",
    //     imageUrl: "https://via.placeholder.com/150",
    //     url: "https://vishal-s-p.github.io/projects/2023/proj_2.html",
        
    // },
    // { 
    //     title: "Project 3",
    //     imageUrl: "https://via.placeholder.com/150",
    //     url: "https://vishal-s-p.github.io/projects/2023/proj_2.html",
        
    // },
    // { 
    //     title: "Project 4",
    //     imageUrl: "https://via.placeholder.com/150",
    //     url: "https://vishal-s-p.github.io/projects/2023/proj_2.html",
        
    // },
    // { 
    //     title: "Project 5",
    //     imageUrl: "https://via.placeholder.com/150",
    //     url: "https://vishal-s-p.github.io/projects/2023/proj_2.html",
        
    // },
    
];

// Function to dynamically create project blocks
function createProjectBlocks() {
    const projectsContainer = document.getElementById("project-list");

    projects.forEach(project => {
        const projectBlock = document.createElement("div");
        projectBlock.classList.add("project");

        const projectContent = document.createElement("div");
        projectContent.classList.add("project-content");

        // Changed from a div to an a element for hyperlink
        const projectTitle = document.createElement("a");
        projectTitle.classList.add("project-title");
        projectTitle.textContent = project.title;
        projectTitle.href = project.url; // Assuming project.url contains the URL to open
        projectTitle.target = "_blank"; // Optional: Opens the link in a new tab
        const projectImage = document.createElement("img");
        projectImage.classList.add("project-image");
        projectImage.src = project.imageUrl;

        // const projectDescription = document.createElement("div");
        // projectDescription.classList.add("project-description");
        // projectDescription.textContent = project.description;

        // Abstract in italics
        const projectAbstract = document.createElement("div");
        projectAbstract.classList.add("project-abstract");
        // Create an italic element to wrap the abstract text
        const italicText = document.createElement("i");
        italicText.textContent = project.abstract; // Use project.abstract or similar
        projectAbstract.appendChild(italicText);


        projectContent.appendChild(projectTitle);
        projectContent.appendChild(projectAbstract);

        projectBlock.appendChild(projectImage);
        projectBlock.appendChild(projectContent);

        projectsContainer.appendChild(projectBlock);
    });
}

// Call the function to create project blocks when the page loads
window.onload = createProjectBlocks;
