#!/usr/bin/env python3
"""
Drop images into moments/img/portfolio/, then run:
    python3 update-gallery.py
from the moments/ directory.

- New images are appended with an empty location ("").
- Existing entries keep their location labels intact.
- Removes entries whose files no longer exist.
"""

import os, re, json
from pathlib import Path

PORTFOLIO_DIR = Path("img/portfolio")
PHOTOS_JS     = Path("photos.js")
EXTENSIONS    = {".jpg", ".jpeg", ".png", ".gif", ".webp"}

# ── 1. Read existing data from photos.js ──────────────────────────────────────
existing = {}   # file -> location
if PHOTOS_JS.exists():
    text = PHOTOS_JS.read_text()
    for m in re.finditer(r'\{\s*file:\s*"([^"]+)",\s*location:\s*"([^"]*)"\s*\}', text):
        existing[m.group(1)] = m.group(2)

# ── 2. Scan the portfolio folder ──────────────────────────────────────────────
found = sorted(
    [f"img/portfolio/{f.name}" for f in PORTFOLIO_DIR.iterdir()
     if f.suffix.lower() in EXTENSIONS],
    key=lambda p: p.lower()
)

# ── 3. Merge: keep order of existing entries, append new ones at the end ──────
merged = []
seen   = set()

# Preserve existing order for files that still exist
for file, loc in existing.items():
    if file in [f for f in found]:
        merged.append((file, loc))
        seen.add(file)

# Append new files not yet in photos.js
new_files = [f for f in found if f not in seen]
if new_files:
    print(f"Adding {len(new_files)} new image(s):")
    for f in new_files:
        print(f"  + {f}  →  location: \"\"  (fill this in)")
        merged.append((f, ""))
else:
    print("No new images found.")

removed = set(existing) - set(found)
if removed:
    print(f"Removed {len(removed)} missing file(s): {removed}")

# ── 4. Write photos.js ────────────────────────────────────────────────────────
lines = [
    "// Auto-generated by update-gallery.py — edit locations here, do not reorder manually.",
    "// Run `python3 update-gallery.py` from the moments/ directory after adding new images.",
    "const PHOTOS = [",
]
for file, loc in merged:
    lines.append(f'  {{ file: "{file}", location: "{loc}" }},')
lines.append("];")

PHOTOS_JS.write_text("\n".join(lines) + "\n")
print(f"\nWrote {len(merged)} entries to {PHOTOS_JS}")
